import { FaEye } from "react-icons/fa";
import "../../styles/reports.css";

function ReportsTable({
  reports,
  onView,
}) {
  return (
    <div className="reports-table-card">

      <table className="reports-table">

        <thead>

          <tr>
            <th>Report ID</th>
            <th>Report Name</th>
            <th>Date</th>
            <th>Generated By</th>
            <th>Status</th>
            <th>Action</th>
          </tr>

        </thead>

        <tbody>

          {reports.length === 0 ? (

            <tr>

              <td
                colSpan="6"
                className="no-data"
              >
                No Reports Available
              </td>

            </tr>

          ) : (

            reports.map((report) => (

              <tr key={report.id}>

                <td>{report.report_id}</td>

                <td>{report.name}</td>

                <td>
                  {new Date(
                    report.report_date
                  ).toLocaleDateString()}
                </td>

                <td>
                  {report.generated_by}
                </td>

                <td>

                  <span
                    className={`report-status ${report.status
                      .toLowerCase()
                      .replace(/\s/g, "-")}`}
                  >
                    {report.status}
                  </span>

                </td>

                <td>

                  <button
                    className="view-btn"
                    onClick={() =>
                      onView(report)
                    }
                  >
                    <FaEye />
                  </button>

                </td>

              </tr>

            ))

          )}

        </tbody>

      </table>

    </div>
  );
}

export default ReportsTable;