import "../../styles/reports.css";

function ViewReportModal({
  report,
  onClose,
}) {
  return (
    <div className="modal-overlay">

      <div className="view-report-modal">

        <div className="modal-header">

          <h2>Report Details</h2>

          <button
            className="close-btn"
            onClick={onClose}
          >
            ✖
          </button>

        </div>

        <div className="view-report-content">

          <p>
            <strong>Report ID:</strong> {report.id}
          </p>

          <p>
            <strong>Report Name:</strong> {report.name}
          </p>

          <p>
            <strong>Date:</strong> {report.date}
          </p>          <p>
            <strong>Generated By:</strong> {report.generatedBy}
          </p>

          <p>
            <strong>Status:</strong>

            <span
              className={`report-status ${report.status
                .toLowerCase()
                .replace(/\s/g, "-")}`}
              style={{ marginLeft: "10px" }}
            >
              {report.status}
            </span>

          </p>

          <div className="report-description">

            <strong>Description:</strong>

            <p>
              {report.description ||
                "No description available for this report."}
            </p>

          </div>

        </div>

        <div className="form-buttons">

          <button
            className="cancel-btn"
            onClick={onClose}
          >
            Close
          </button>

        </div>

      </div>

    </div>
  );
}

export default ViewReportModal;