import { useState, useEffect } from "react";
import axios from "axios";
import { saveAs } from "file-saver";

import Layout from "../components/layout/Layout";
import ReportsHeader from "../components/reports/ReportsHeader";
import ReportsCards from "../components/reports/ReportsCards";
import ReportsCharts from "../components/reports/ReportsCharts";
import ReportsTable from "../components/reports/ReportsTable";
import ViewReportModal from "../components/reports/ViewReportModal";

function Reports() {
  const [reports, setReports] = useState([]);

  const [searchTerm, setSearchTerm] = useState("");

  const [viewReport, setViewReport] = useState(null);

  const [totalProducts, setTotalProducts] = useState(0);

  const [totalSuppliers, setTotalSuppliers] = useState(0);

  const [totalWarehouses, setTotalWarehouses] = useState(0);

  const [totalInventory, setTotalInventory] = useState(0);

  useEffect(() => {
    fetchReports();
    fetchCounts();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await axios.get(
        "http://localhost:5000/api/reports"
      );

      setReports(res.data);
    } catch (error) {
      console.log(error);
    }
  };

  const fetchCounts = async () => {
    try {
      const [
        products,
        suppliers,
        warehouses,
        inventory,
      ] = await Promise.all([
        axios.get("http://localhost:5000/api/products"),
        axios.get("http://localhost:5000/api/suppliers"),
        axios.get("http://localhost:5000/api/warehouses"),
        axios.get("http://localhost:5000/api/inventory"),
      ]);

      setTotalProducts(products.data.length);

      setTotalSuppliers(suppliers.data.length);

      setTotalWarehouses(warehouses.data.length);

      setTotalInventory(inventory.data.length);
    } catch (error) {
      console.log(error);
    }
  };

  const filteredReports = reports.filter(
    (report) =>
      report.name
        .toLowerCase()
        .includes(searchTerm.toLowerCase()) ||

      report.generated_by
        .toLowerCase()
        .includes(searchTerm.toLowerCase())
  );

  const exportReport = () => {
    const csvData = [
      [
        "Report ID",
        "Report Name",
        "Date",
        "Generated By",
        "Status",
      ],

      ...filteredReports.map((report) => [
        report.report_id,
        report.name,
        report.report_date,
        report.generated_by,
        report.status,
      ]),
    ];

    const csvContent = csvData
      .map((row) => row.join(","))
      .join("\n");

    const blob = new Blob([csvContent], {
      type: "text/csv;charset=utf-8;",
    });

    saveAs(blob, "Inventory_Report.csv");
  };

  return (
    <Layout>

      <ReportsHeader
        searchTerm={searchTerm}
        setSearchTerm={setSearchTerm}
        onExport={exportReport}
      />

      <ReportsCards
        totalProducts={totalProducts}
        totalSuppliers={totalSuppliers}
        totalWarehouses={totalWarehouses}
        totalInventory={totalInventory}
      />

      <ReportsCharts
        totalProducts={totalProducts}
        totalSuppliers={totalSuppliers}
        totalWarehouses={totalWarehouses}
        totalInventory={totalInventory}
      />

      <ReportsTable
        reports={filteredReports}
        onView={(report) =>
          setViewReport(report)
        }
      />

      {viewReport && (
        <ViewReportModal
          report={viewReport}
          onClose={() =>
            setViewReport(null)
          }
        />
      )}

    </Layout>
  );
}

export default Reports;