import { useState } from "react";
import { saveAs } from "file-saver";

import Layout from "../components/layout/Layout";
import ReportsHeader from "../components/reports/ReportsHeader";
import ReportsCards from "../components/reports/ReportsCards";
import ReportsCharts from "../components/reports/ReportsCharts";
import ReportsTable from "../components/reports/ReportsTable";
import ViewReportModal from "../components/reports/ViewReportModal";

function Reports() {
  const [searchTerm, setSearchTerm] = useState("");
  const [viewReport, setViewReport] = useState(null);

  const reportsData = [
    {
      id: "REP-1001",
      name: "Monthly Inventory Report",
      date: "10 Jul 2026",
      generatedBy: "Admin",
      status: "Completed",
    },
    {
      id: "REP-1002",
      name: "Supplier Performance",
      date: "08 Jul 2026",
      generatedBy: "Manager",
      status: "Completed",
    },
    {
      id: "REP-1003",
      name: "Warehouse Stock Report",
      date: "05 Jul 2026",
      generatedBy: "Admin",
      status: "Pending",
    },
    {
      id: "REP-1004",
      name: "Purchase Orders Report",
      date: "01 Jul 2026",
      generatedBy: "Manager",
      status: "Completed",
    },
  ];

  const filteredReports = reportsData.filter(
    (report) =>
      report.name
        .toLowerCase()
        .includes(searchTerm.toLowerCase()) ||
      report.generatedBy
        .toLowerCase()
        .includes(searchTerm.toLowerCase())
  );

  const exportReport = () => {
    const csvData = [
      [
        "Report ID",
        "Report Name",
        "Date",
        "Generated By",
        "Status",
      ],

      ...filteredReports.map((report) => [
        report.id,
        report.name,
        report.date,
        report.generatedBy,
        report.status,
      ]),
    ];

    const csvContent = csvData
      .map((row) => row.join(","))
      .join("\n");

    const blob = new Blob([csvContent], {
      type: "text/csv;charset=utf-8;",
    });

    saveAs(blob, "Inventory_Report.csv");
  };

  return (
    <Layout>
      <ReportsHeader
        searchTerm={searchTerm}
        setSearchTerm={setSearchTerm}
        onExport={exportReport}
      />

      <ReportsCards
        totalProducts={
          JSON.parse(localStorage.getItem("products"))?.length || 0
        }
        totalSuppliers={
          JSON.parse(localStorage.getItem("suppliers"))?.length || 0
        }
        totalWarehouses={
          JSON.parse(localStorage.getItem("warehouses"))?.length || 0
        }
        totalInventory={
          JSON.parse(localStorage.getItem("inventory"))?.length || 0
        }
      />

      <ReportsCharts
        totalProducts={
          JSON.parse(localStorage.getItem("products"))?.length || 0
        }
        totalSuppliers={
          JSON.parse(localStorage.getItem("suppliers"))?.length || 0
        }
        totalWarehouses={
          JSON.parse(localStorage.getItem("warehouses"))?.length || 0
        }
        totalInventory={
          JSON.parse(localStorage.getItem("inventory"))?.length || 0
        }
      />

      <ReportsTable
        reports={filteredReports}
        onView={(report) => setViewReport(report)}
      />

      {viewReport && (
        <ViewReportModal
          report={viewReport}
          onClose={() => setViewReport(null)}
        />
      )}
    </Layout>
  );
}

export default Reports;